Refactor/Feat: Handle ILP packets
interledgerjs/ilp-protocol-ccp pull request #3
Opened 2019-02-26 12:50 UTC by matdehaast

Refactor the various functions to allow for unserialised ILP packets to get the data out of the CCP Requests and Updates

2019-03-01 07:02 UTC, adrianhopebailie approved these changes
LGTM

2019-03-01 14:56 UTC, sentientwaffle requested changes
Please add tests for the new functions

2019-05-29 12:43 UTC, matdehaast commented
> Please add tests for the new functions

@sentientwaffle added the required test coverage to new tests

2019-05-29 14:36 UTC, sentientwaffle approved these changes

2019-05-30 10:58 UTC, merged